# example:
# email_config:
#   from: you@yourdomain.com
#   password: your_password_here
# users:
#   "User 1 Full Name as found in git blame":"associated_email1@domain.com@"
#   "User 2 Full Name as found in git blame":"associated_email2@domain.com@"
